services:
  docs:
    build:
      dockerfile: apps/docs/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
  www:
    build:
      dockerfile: apps/www/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
